name: ci

on:
  push:
  schedule:
    - cron: "55 10,12,14,16,18,20,22 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "joesonshaw@gmail.com"
          git config --local user.name "joesonshaw"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
